// Code generated by mockery v2.46.2. DO NOT EDIT.

package mocks

import (
	io "io"

	types "github.com/google/go-containerregistry/pkg/v1/types"
	mock "github.com/stretchr/testify/mock"

	v1 "github.com/google/go-containerregistry/pkg/v1"
)

// Layer is an autogenerated mock type for the Layer type
type Layer struct {
	mock.Mock
}

// Compressed provides a mock function with given fields:
func (_m *Layer) Compressed() (io.ReadCloser, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Compressed")
	}

	var r0 io.ReadCloser
	var r1 error
	if rf, ok := ret.Get(0).(func() (io.ReadCloser, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() io.ReadCloser); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.ReadCloser)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DiffID provides a mock function with given fields:
func (_m *Layer) DiffID() (v1.Hash, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for DiffID")
	}

	var r0 v1.Hash
	var r1 error
	if rf, ok := ret.Get(0).(func() (v1.Hash, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() v1.Hash); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(v1.Hash)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Digest provides a mock function with given fields:
func (_m *Layer) Digest() (v1.Hash, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Digest")
	}

	var r0 v1.Hash
	var r1 error
	if rf, ok := ret.Get(0).(func() (v1.Hash, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() v1.Hash); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(v1.Hash)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MediaType provides a mock function with given fields:
func (_m *Layer) MediaType() (types.MediaType, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for MediaType")
	}

	var r0 types.MediaType
	var r1 error
	if rf, ok := ret.Get(0).(func() (types.MediaType, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() types.MediaType); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(types.MediaType)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Size provides a mock function with given fields:
func (_m *Layer) Size() (int64, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Size")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func() (int64, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() int64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Uncompressed provides a mock function with given fields:
func (_m *Layer) Uncompressed() (io.ReadCloser, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Uncompressed")
	}

	var r0 io.ReadCloser
	var r1 error
	if rf, ok := ret.Get(0).(func() (io.ReadCloser, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() io.ReadCloser); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.ReadCloser)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewLayer creates a new instance of Layer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLayer(t interface {
	mock.TestingT
	Cleanup(func())
}) *Layer {
	mock := &Layer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
