comment:
  layout: "header, diff, files, footer"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true
  hide_project_coverage: false
coverage:
  status:
    project:
      default:
        threshold: 1%
ignore:
  - pkg/generated
  - api