{{- if and .Values.persistence.enabled .Values.persistence.storageData.enabled (not .Values.persistence.storageData.existingClaim) }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "sbombastic.fullname" . }}-storage-data
  labels:
    {{ include "sbombastic.labels" .| nindent 4 }}
    app.kubernetes.io/component: storage
  {{- with .Values.persistence.storageData.labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  annotations:
  {{- with .Values.persistence.storageData.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    - {{ .Values.persistence.storageData.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.storageData.size | quote }}
  {{- if hasKey .Values.persistence.storageData "storageClass" }}
  storageClassName: "{{ .Values.persistence.storageData.storageClass }}"
  {{- end }}
{{- end }}
