apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "sbombastic.fullname" . }}-worker
  labels:
    {{ include "sbombastic.labels" .| nindent 4 }}
    app.kubernetes.io/component: worker
rules:
  - apiGroups:
      - sbombastic.rancher.io
    resources:
      - registries
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - sbombastic.rancher.io
    resources:
      - registries/finalizers
    verbs:
      - update
  - apiGroups:
      - sbombastic.rancher.io
    resources:
      - registries/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - storage.sbombastic.rancher.io
    resources:
      - images
      - sboms
      - vulnerabilityreports
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
