# {{ if .Values.storage.cnpg.createCluster }}
# Example of PostgreSQL cluster
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-example
  namespace: {{ .Release.Namespace }}
spec:
  instances: 1

  # Example of rolling update strategy:
  # - unsupervised: automated update of the primary once all
  #                 replicas have been upgraded (default)
  # - supervised: requires manual supervision to perform
  #               the switchover of the primary
  primaryUpdateStrategy: unsupervised

  # Require 1Gi of space
  storage:
    size: 1Gi
# apiVersion: postgresql.cnpg.io/v1
# kind: Cluster
# metadata:
#   name: {{ .Values.storage.cnpg.fullnameOverride }}
# spec:
#   instances: 1

#   bootstrap:
#     initdb:
#       database: sbombastic
#       owner: sbombastic
#       secret:
#         name: "" # cnpg will create a secret with the name of the database owner

#   postgresql:
#     pg_hba:
#       - hostssl all all 0.0.0.0/0 scram-sha-256 clientcert=verify-full # mTLS for all connections
#       - hostnossl all all 0.0.0.0/0 reject

#   # NOTE: prefix sbombastic can be changed to result of {{ include "sbombastic.fullname" . }}
#   certificates:
#     serverCASecret:   sbombastic-cnpg-server-cert
#     serverTLSSecret:  sbombastic-cnpg-server-cert
#     clientCASecret:   sbombastic-cnpg-client-cert
#     replicationTLSSecret: sbombastic-cnpg-client-cert

#   storage:
#     size: 1Gi
#     # storageClass: # Specify the storage class to use. If defined, ensure it has reclaimPolicy: Retain to prevent data loss if the cluster is accidentally deleted
# {{ end }}