// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

type Image struct {
	ID        int32
	Name      string
	Namespace string
	Object    string
}

type Sbom struct {
	ID        int32
	Name      string
	Namespace string
	Object    string
}

type Vulnerabilityreport struct {
	ID        int32
	Name      string
	Namespace string
	Object    string
}
